apiVersion: core.jenkins-x.io/v4beta1
kind: Requirements
spec:
  autoUpdate:
    enabled: false
    schedule: ""
  cluster:
    chartRepository: http://jenkins-x-chartmuseum.jx.svc.cluster.local:8080
    clusterName: lfs268-lab
    dockerRegistryOrg: oci
    environmentGitOwner: todo
    gitKind: github
    gitName: github
    gitServer: https://github.com
    gke:
      projectNumber: "349571583085"
    kanikoFlags: --skip-unused-stages --snapshotMode=redo
    project: ci-cd-349400
    provider: gke
    registry: us-central1-docker.pkg.dev/ci-cd-349400
    zone: us-central1-a
  environments:
  - key: dev
    owner: lfs268-eeganlf
    repository: jx3-gke-gsm
  - key: staging
  - key: production
  ingress:
    domain: ""
    kind: ingress
    namespaceSubDomain: -jx.
    tls:
      email: ""
      enabled: false
      production: true
  pipelineUser:
    username: eeganlf
  repository: nexus
  secretStorage: gsm
  storage:
  - name: logs
    url: gs://logs-lfs268-lab-18b600a74ae2
  - name: reports
    url: gs://reports-lfs268-lab-18b600a74ae2
  - name: repository
    url: gs://repository-lfs268-lab-18b600a74ae2
  vault: {}
  webhook: lighthouse
