environments:
  default:
    values:
    - jx-values.yaml
---
namespace: jx-staging
repositories:
- name: jxgh
  url: https://jenkins-x-charts.github.io/repo
- name: dev
  url: http://chartmuseum-jx.136.114.174.212.nip.io
releases:
- chart: jxgh/jx-verify
  name: jx-verify
  namespace: jx-staging
  values:
  - jx-values.yaml
- chart: dev/golab
  version: 0.0.1
  name: golab
  values:
  - jx-values.yaml
